### Listar todos os Livros
GET http://localhost:5231/api/livros

### Cadastrar Livro
POST http://localhost:5231/api/livros
Content-Type: application/json

{
 "Titulo":"Senhor",
 "Autor":"Josh",
 "CategoriaId": 2 
}

### Listar livros pelo id
GET http://localhost:5231/api/livros/3

### Atualizar Livro
PUT http://localhost:5231/api/livros/3
Content-Type: application/json

{
 "Titulo":"Harry Potter",
 "Autor":"J.K. Roaling",
 "CategoriaId": 5 
}


